### PR TITLE
Move handle_sched_getaffinity to linux section

### PR DESCRIPTION
**Pull request by jcalvert**
Trying to compile on OS X (10.11) and `make` fails with:

```
syscall.c:176:2: error: use of undeclared identifier 'cpu_set_t'
        cpu_set_t *mask;
        ^
syscall.c:176:13: error: use of undeclared identifier 'mask'
        cpu_set_t *mask;
                   ^
syscall.c:180:2: error: use of undeclared identifier 'mask'
        mask = va_arg(args, __typeof__(mask));
        ^
syscall.c:180:33: error: use of undeclared identifier 'mask'
        mask = va_arg(args, __typeof__(mask));
                                       ^
syscall.c:182:29: error: use of undeclared identifier 'SYS_sched_getaffinity'
        return tsocks_libc_syscall(TSOCKS_NR_SCHED_GETAFFINITY, pid, cpusetsize,
                                   ^
../../src/common/compat.h:195:37: note: expanded from macro 'TSOCKS_NR_SCHED_GETAFFINITY'
#define TSOCKS_NR_SCHED_GETAFFINITY SYS_sched_getaffinity
                                    ^
syscall.c:183:4: error: use of undeclared identifier 'mask'
                        mask);
```

Moving this call into the `defined(__linux__)` section allows compilation to succeed.

### CODE REVIEW

**Comment by dgoulet** [comment]
Thanks for this! Hrm... so that call seems to exists on FreeBSD though (and other BSDs) but OS X decided to not have it...

I'll move it in a section protected with:
`if !defined(__darwin__)`

Let me know if it works for you and/or doesn't make sense :)

**Comment by jcalvert** [comment]
Makes sense to me. Thanks!
